# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'SongwriterStudioPro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'AudioKit',   '~> 4.0'
  pod 'Disk', '~> 0.3.3'
  # Pods for SongwriterStudioPro

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0.3'
          end
      end
  end
end

